Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed Someone's PC.$"

gText_StorageSystemOpened::
	.string "Pokémon Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed Lanette's PC.$"

gText_AccessedBillsPC::
	.string "Accessed Bill's PC.$"
